name: mariner
description: "Oprogramowanie dla żeglarzy"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  http: ^1.2.2
  provider: ^5.0.0
  auto_route: ^9.2.2
  image_picker: ^1.1.2
  cross_file_image: ^1.1.0
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
